# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('ordinal',), 'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='recipe',
            name='yields',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
